###### 为实现多个功能模块公用一个 Provider，那么必须允许 Provider 重名
spring:
  main:
    allow-bean-definition-overriding: true
###### Eureka Client 连接注册中心信息
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9999/eureka
###### 配置 OpenFeign 超时时间
### hystrix 的超时时间
hystrix:
  command:
    default:
      execution:
        timeout:
          enableb: true
        isolation:
          thread:
            timeoutlnMilliseconds: 8000
#ribbon 的超时时间
ribbon:
    ReadTimeout: 8000
    ConnectTimeout: 8000